{% set name = "hxnfly" %}
{% set version = "0.0.7" %}
{% set sha256 = "cf4f22c7e49857fef6fd2fc96831a562c34673df13d83fb7e37547283d154864" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II-HXN/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - hxntools
    - ppmac
    - xray-vision

test:
  imports:
    - hxnfly

about:
  home: https://github.com/NSLS-II-HXN/hxnfly
  license: BSD
  license_file: LICENSE
  summary: Tools for NSLS-II HXN fly scans
