{% set name = "hxnfly" %}
{% set version = "0.0.5" %}
{% set sha256 = "b6e1280e59929c6e0eabe4ad27a0b52d4bb0cc785ac7781b999e75643985b7f3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II-HXN/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - hxntools
    - ppmac
    - xray-vision

test:
  imports:
    - hxnfly

about:
  home: https://github.com/NSLS-II-HXN/hxnfly
  license: BSD
  license_file: LICENSE
  summary: Tools for NSLS-II HXN fly scans
